version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped

    volumes:
      - /app/node_modules
      - ./frontend:/app

  server:
    container_name: server
    build: ./server
    restart: unless-stopped

    volumes:
      - /app/node_modules
      - ./server:/app

    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw

  redis:
    container_name: redis
    image: redis:alpine

    command: ["redis-server", "--appendonly", "yes"]

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - ./server/data/redis:/data

volumes:
  postgres:
  redis:
