version: "3"
services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /app/node_modules
  #     - .:/app

  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./server/data/redis:/data

volumes:
  postgres:
  redis:
