version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

  server:
    build:
      context: server
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]
