version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend

    volumes:
      - /app/node_modules
      - ./frontend:/app

  server:
    container_name: server
    build: ./server
    
    volumes:
      - /app/node_modules
      - ./server:/app

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
    

  redis:
    container_name: redis
    image: redis:alpine

    # command: ["redis-server", "--appendonly", "yes"]
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - ./server/data/redis:/data

volumes:
  postgres:
  redis:
